### ISSUE TITLE
Generates empty PNGs on Phantom 2.0

### ISSUE THREAD

**Issue by Kreozot** [justim/postcss-svg-fallback#12]
Anybody testing with Phantom 2.0?

**Comment by Kreozot** [comment]
Looks like problem was in resizing images.

**Comment by Kreozot** [comment]
Resizing fails if SVG doesn't have x and y parameters.

**Comment by justim** [comment]
Thanks for figuring that out, I think we should add that to the README to clarify the empty PNGs in some cases. I'll investigate a bit to see if there are any more conditions to which the SVG should comply.
