### ISSUE TITLE
Path for images from inline SVGs

### ISSUE THREAD

**Issue by SlivTime** [justim/postcss-svg-fallback#19]
Images, generated from inline SVGs are stored in **dest** path, but url for them does not consider this fact. Browser tries to find this images near the css files and gets 404. I assume that we need to add one more option (something like **destUrlPrefix**) and add it before generated file name in css. If it is ok, I can write this feature and make PR.

**Comment by justim** [comment]
If you set the `dest` option to something like `build` and you put the resulting CSS in the same directory, you should be fine, right? The same is the case for normal images.

Maybe I'm missing a use case?

**Comment by justim** [comment]
Closing this as it's either resolved, or not an issue anymore. Feel free to re-open.
