### ISSUE TITLE
Only 36 stars? :O

### ISSUE THREAD

**Issue by mikeaustin** [justim/postcss-svg-fallback#22]
I didn't see a gitter.im channel or other source of communication, so my apologies for posting here.

I was just curious, this seems super helpful, but only has 36 stars and 1 dependent. The project name is perfect. The project sounds like it solves a real problem. I'm exploring new plugins to start a new project, and using strictly SVG for icons would be very handy (no design change issues).

**Comment by justim** [comment]
It is indeed a real problem solver, but only if you need to support browsers that don't support SVG, which [aren't really used anymore](http://caniuse.com/#search=svg).

Thanks for reaching out!
