### ISSUE TITLE
Option to disable PhantomJS, just modify CSS

### ISSUE THREAD

**Issue by tbredin** [justim/postcss-svg-fallback#6]
My use case: I'm using `gulp-svg2png` to convert my svgs as it detects the size from the svg itself, and I can progressively use `background-size` like `auto` or `100%` for newer browsers. 

Would be great to get an option for outputting just the CSS output component of this plugin!

**Comment by vkhv** [comment]
+1

**Comment by justim** [comment]
Thanks for the suggestion, guys.
