### ISSUE TITLE
Windows 10 path to svg

### ISSUE THREAD

**Issue by npofopr** [justim/postcss-svg-fallback#9]
Plugin don't generate fallback png:

```
postcss-svg-fallback: D:\Docs\Dropbox\!Project\test_svg_fallback\src\css\style.css:1:1: Could not find "../images/icon_reg.svg" at "D:\Docs\Dropbox\!Project\images\icon_reg.svg"
postcss-svg-fallback: D:\Docs\Dropbox\!Project\test_svg_fallback\src\css\style.css:7:1: Could not find "../images/svg/icon_reg.svg" at "D:\Docs\Dropbox\!Project\images\svg\icon_reg.svg"
```

Example https://github.com/npofopr/test_postcss-svg-fallback 

Write `basePath` and `dest` don't help me.

What am i doing wrong?

**Comment by justim** [comment]
Thanks for the great reproduction! :)

I figured out what's wrong, the options given to the plugin are not right. You need the following to make it work in your test case:

``` js
svgFallback({
    basePath: 'src/css', // location of the input css
    dest: 'build/css', // location of the output css
})
```

But I would like to update the docs/code to prevent people using the right configuration. What would have helped you better setting the right options?

I have a couple of suggestions:
- Add a note that the `basePath` is the location of the stylesheet most of the time and `dest` is most of the times just the location of output css. These paths unfortunately are impossible to figure out by the plugin.
- Make the `basePath` and the `dest` mandatory and give better feedback when a file is not found about these options

Maybe anything else?

**Comment by npofopr** [comment]
Thanks, i think

```
basePath: '', // base path for the images found in the css
dest: '', // destination for the generated SVGs
```

this path for images :)

png create, but svg don't copy in dest folder, it is right?

**Comment by justim** [comment]
This plugin indeed doesn't copy the SVG files, it only generates the PNG files based on the SVG files found in the CSS.
